name: Build and Package Fyne App

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Fyne App
    runs-on: macos-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: Install fyne-cross
      run: go install github.com/fyne-io/fyne-cross@latest

    - name: Build Fyne App for Darwin
      run: fyne-cross darwin -name "Textstorm" -icon big_icon.png -app-id se.stenstromen.textstorm -app-version ${{ env.VERSIONTAG }} -release
      env:
        VERSIONTAG: 1.0.0
        PATH: ${{ github.workspace }}/go/bin:$PATH

    - name: Zip the Textstorm.app bundle
      run: zip -r Textstorm.zip fyne-cross/dist/darwin-amd64/Textstorm.app

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Textstorm-MacOS
        path: Textstorm.zip
